// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_run_tabu_search
Rcpp::List cpp_run_tabu_search(Rcpp::NumericMatrix X_in, Rcpp::IntegerVector y_in, double b0, int d, int iSeed);
RcppExport SEXP _hitsr_cpp_run_tabu_search(SEXP X_inSEXP, SEXP y_inSEXP, SEXP b0SEXP, SEXP dSEXP, SEXP iSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type iSeed(iSeedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_run_tabu_search(X_in, y_in, b0, d, iSeed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hitsr_cpp_run_tabu_search", (DL_FUNC) &_hitsr_cpp_run_tabu_search, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_hitsr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
